import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

export const sendSubscriptionMail = async ({ email }) => {
  const transporter = nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    auth: {
      user: process.env.NODE_MAILER_EMAIL,
      pass: process.env.NODE_MAILER_PASSWORD,
    },
  });

  const htmlTemplate = `
    <html>
      <body style="font-family: 'Segoe UI', sans-serif; background-color: #0d0d0d; padding: 30px; color: #ffffff;">
        <table width="100%" style="max-width: 600px; margin: auto; background: #1a1a1a; border-radius: 12px; overflow: hidden; box-shadow: 0 0 15px rgba(0,0,0,0.6);">
          
          <tr>
            <td style="background-color: #111111; padding: 24px; text-align: center;">
              <h2 style="margin: 0; font-size: 24px; color: #00e6b8;">🚀 New Subscription Alert</h2>
              <p style="margin-top: 8px; font-size: 14px; color: #ccc;">from your CoderCamp Website</p>
            </td>
          </tr>

          <tr>
            <td style="padding: 30px; text-align: center;">
              <p style="font-size: 16px; color: #aaa;">You’ve got a new subscriber interested in your updates!</p>
              <p style="font-size: 20px; color: #ffffff; font-weight: bold; margin-top: 10px;">${email}</p>
            </td>
          </tr>

          <tr>
            <td style="background-color: #0f0f0f; padding: 20px; text-align: center;">
              <p style="margin: 0; font-size: 13px; color: #888;">
                Add this email to your newsletter or CRM tool for future campaigns. <br/>
                Build the CoderCamp community, one client at a time. 🔥
              </p>
            </td>
          </tr>

          <tr>
            <td style="padding: 16px; background-color: #0d0d0d; text-align: center;">
              <small style="color: #666;">
                💻 This message was generated by your agency site – <strong>CoderCamp.in</strong>
              </small>
            </td>
          </tr>

        </table>
      </body>
    </html>
  `;

  await transporter.sendMail({
    from: `"CoderCamp Newsletter Bot" <${process.env.NODE_MAILER_EMAIL}>`,
    to: process.env.Node_MAILER_Reciver,
    subject: " New Subscriber via CoderCamp",
    html: htmlTemplate,
  });
};
